services:
  - docker

before_script:
  - cp ./nginx.sh ./test/nginx/debian7/
  - cp ./nginx.sh ./test/nginx/debian8/


script:
  - docker build ./test/nginx/debian7
  - docker build ./test/nginx/debian8